# Generated by Django 4.2.4 on 2023-08-25 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True, verbose_name='Телефон'),
        ),
    ]
