# Generated by Django 4.2.4 on 2023-08-25 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department', to='employees.department'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='device',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='device', to='employees.device'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='dossier',
            field=models.CharField(blank=True, choices=[('YES', 'Да'), ('NO', 'Нет')], default='NO', max_length=3, verbose_name='Досье сотрудника'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='position',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='position', to='employees.position'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(blank=True, choices=[('YES', 'Да'), ('NO', 'Нет')], default='NO', max_length=3, verbose_name='Статус отслеживания'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user_lic',
            field=models.CharField(blank=True, choices=[('YES', 'Да'), ('NO', 'Нет')], default='NO', max_length=3, verbose_name='Лицензия пользователя'),
        ),
    ]
